Repository pmgbergen/porepy, pull requests merged in 2022-10, with the labels that each got.

#738 Partial integration of time-stepping control into models
  src/porepy/__init__.py
  src/porepy/models/contact_mechanics_biot_model.py
  src/porepy/models/run_models.py
  src/porepy/models/slightly_compressible_flow_model.py
  src/porepy/models/thm_model.py
  src/porepy/numerics/time_step_control.py
  tests/common/contact_mechanics_examples.py
  tests/integration/test_ad_equations.py
  tests/integration/test_contact_mechanics_biot.py
  tests/integration/test_dilation.py
  tests/integration/test_thm.py
  tests/unit/test_time_step_control.py
Labels: enhancement, review - short

#746 FEAT: Sorting of grids within mdgs
  src/porepy/fracs/meshing.py
  src/porepy/grids/grid.py
  src/porepy/grids/match_grids.py
  src/porepy/grids/md_grid.py
  src/porepy/grids/mortar_grid.py
  src/porepy/numerics/interface_laws/elliptic_interface_laws.py
  src/porepy/numerics/interface_laws/hyperbolic_interface_laws.py
  src/porepy/utils/derived_discretizations/implicit_euler.py
  src/porepy/viz/exporter.py
  src/porepy/viz/plot_grid.py
  tests/integration/_helper_test_upwind_coupling.py
  tests/integration/test_DFN.py
  tests/integration/test_TpfaMonoCoupling.py
  tests/integration/test_upwind_coupling.py
  tests/test_grids.py
  tests/unit/test_assembler.py
  tests/unit/test_darcy_mortar.py
  tests/unit/test_grid.py
  tests/unit/test_md_grid.py
  tests/unit/test_mixed_dim_gravity.py
  tests/unit/test_mortars.py
  tests/unit/test_vtk.py
  tests/unit/test_vtk_reference/constant_data_test_grid_2.vtu
  tests/unit/test_vtk_reference/constant_data_test_grid_constant_2.vtu
  tests/unit/test_vtk_reference/fractures_2d.vtu
  tests/unit/test_vtk_reference/fractures_3d.vtu
  tests/unit/test_vtk_reference/mdg_data_selection_grid_1.vtu
  tests/unit/test_vtk_reference/mdg_data_selection_grid_2.vtu
  tests/unit/test_vtk_reference/mdg_data_selection_grid_mortar_1.vtu
  tests/unit/test_vtk_reference/mdg_grid_1.vtu
  tests/unit/test_vtk_reference/mdg_grid_2.vtu
  tests/unit/test_vtk_reference/mdg_grid_mortar_1.vtu
  tests/unit/test_vtk_reference/single_subdomain_1d.vtu
  tests/unit/test_vtk_reference/single_subdomain_2d_cart_grid.vtu
  tests/unit/test_vtk_reference/single_subdomain_2d_polytop_grid.vtu
  tests/unit/test_vtk_reference/single_subdomain_2d_simplex_grid.vtu
  tests/unit/test_vtk_reference/single_subdomain_3d_cart_grid.vtu
  tests/unit/test_vtk_reference/single_subdomain_3d_polytop_grid.vtu
  tests/unit/test_vtk_reference/single_subdomain_3d_simplex_grid.vtu
Labels: priority - high, PR - waiting on reviewer(s)

#745 Adaptive interpolation tables
  .gitignore
  src/porepy/__init__.py
  src/porepy/numerics/ad/operator_functions.py
  src/porepy/utils/array_operations.py
  src/porepy/utils/interpolation_tables.py
  tests/unit/test_array_operations.py
  tests/unit/test_interpolation_tables.py
Labels: enhancement, PR - waiting on reviewer(s)
