Repository pmgbergen/porepy, pull requests merged in 2022-08, with the labels that each got.

#665 Bugfix AD arithmetics
  src/porepy/numerics/ad/operators.py
Labels: bug-fix

#681 Stand-alone point in polyhedron test
  .github/workflows/ci.yml
  .gitignore
  Install.md
  fetch_content.py
  src/porepy/__init__.py
  src/porepy/geometry/geometry_property_checks.py
  src/porepy/geometry/point_in_polyhedron_test.py
  tests/unit/test_mpfa_gravity.py
  tests/unit/test_tag.py
Labels: enhancement, dependencies

#661 Ad operator functions
  src/porepy/numerics/ad/__init__.py
  src/porepy/numerics/ad/operator_functions.py
  src/porepy/numerics/ad/operators.py
  tests/unit/test_ad.py
Labels: enhancement
