Repository pmgbergen/porepy, pull requests merged in 2022-09, with the labels that each got.

#710 BLD: separate reqs and reqs-dev
  .github/workflows/ci.yml
  dockerfiles/base/Dockerfile
  requirements-dev.txt
  requirements.txt
Labels: dependencies, 5 - ready to merge, effort - short, review effort - short, priority - medium

#718 BUG: Use meshio's convention to define cell types.
  src/porepy/viz/exporter.py
Labels: 3 - ready for review, review effort - short

#716 FEAT: Split assemble_and_solve_linear_system
  src/porepy/models/abstract_model.py
  src/porepy/numerics/linear_solvers.py
  src/porepy/numerics/nonlinear/nonlinear_solvers.py
  tests/integration/test_ad_equations.py
Labels: 3 - ready for review, review effort - short, priority - high

#727 DOC: Update pull_request_template.md
  .github/pull_request_template.md
Labels: 4 - waiting on reviewer, effort - short, doc - improve

#729 BLD: Pin version of python 3.10 to 3.10.6
  .github/workflows/ci.yml
Labels: 3 - ready for review, review effort - short

#720 Add possibility to use constant time step in the `TimeSteppingControl` class
  src/porepy/numerics/time_step_control.py
  tests/unit/test_time_step_control.py
Labels: enhancement, review - short
