Repository pmgbergen/porepy, pull requests merged in 2022-11, with the labels that each got.

#761 Allow for tolerance specification in `domain_boundary_sides()`
  src/porepy/models/abstract_model.py
Labels: enhancement, review - short

#766 MAINT: Refactor of domain boundary sides
  src/porepy/models/abstract_model.py
Labels: enhancement, review - short

#763 Maint ad docs
  src/porepy/numerics/ad/functions.py
  src/porepy/numerics/ad/operator_functions.py
  src/porepy/numerics/ad/operators.py
Labels: documentation

#768 Synchronize docs develop
  .github/CODEOWNERS
  mypy.ini
  src/porepy/fracs/fracture_importer.py
  src/porepy/fracs/fracture_network_2d.py
  src/porepy/fracs/fracture_network_3d.py
  src/porepy/fracs/gmsh_interface.py
  src/porepy/fracs/meshing.py
  src/porepy/fracs/msh_2_grid.py
  src/porepy/fracs/structured.py
  src/porepy/fracs/wells_3d.py
  src/porepy/grids/md_grid.py
  src/porepy/grids/mortar_grid.py
  src/porepy/grids/partition.py
  src/porepy/grids/point_grid.py
  src/porepy/grids/standard_grids/md_grids_2d.py
  src/porepy/grids/standard_grids/utils.py
  src/porepy/models/abstract_model.py
  src/porepy/numerics/ad/equation_manager.py
  src/porepy/numerics/ad/functions.py
  src/porepy/numerics/ad/operator_functions.py
  src/porepy/numerics/ad/operators.py
  src/porepy/numerics/fv/fvutils.py
  src/porepy/numerics/fv/mpsa.py
  src/porepy/numerics/interface_laws/elliptic_interface_laws.py
  src/porepy/numerics/linear_solvers.py
  src/porepy/numerics/mixed_dim/assembler.py
  src/porepy/numerics/vem/dual_elliptic.py
  src/porepy/params/data.py
  src/porepy/py.typed
Labels: documentation

#772 BLD: Updates to github actions workflow
  .github/workflows/ci.yml
Labels: PR - waiting on reviewer(s), review - short
