Repository pmgbergen/porepy, pull requests merged in 2023-03, with the labels that each got.

#827 DEP: Remove unused operators and their tests
  src/porepy/numerics/ad/grid_operators.py
  tests/unit/ad/test_grid_operators.py
Labels: PR - waiting on author(s)

#830 Model_wells
  src/porepy/fracs/fracture_importer.py
  src/porepy/fracs/fracture_network_2d.py
  src/porepy/fracs/fracture_network_3d.py
  src/porepy/fracs/structured.py
  src/porepy/fracs/wells_3d.py
  src/porepy/grids/grid.py
  src/porepy/grids/md_grid.py
  src/porepy/models/constitutive_laws.py
  src/porepy/models/energy_balance.py
  src/porepy/models/fluid_mass_balance.py
  src/porepy/models/geometry.py
  src/porepy/models/mass_and_energy_balance.py
  src/porepy/models/material_constants.py
  src/porepy/models/momentum_balance.py
  src/porepy/models/poromechanics.py
  src/porepy/models/thermoporomechanics.py
  src/porepy/numerics/ad/equation_system.py
  src/porepy/numerics/ad/grid_operators.py
  src/porepy/numerics/fracture_deformation/contact_conditions.py
  src/porepy/viz/data_saving_model_mixin.py
  src/porepy/viz/exporter.py
  tests/functional/setups/manu_flow_comp_frac.py
  tests/integration/models/setup_utils.py
  tests/integration/models/test_constitutive_laws.py
  tests/integration/models/test_energy_balance.py
  tests/integration/models/test_equations.py
  tests/integration/models/test_geometry.py
  tests/integration/models/test_mass_balance.py
  tests/integration/models/test_momentum_balance.py
  tests/integration/models/test_poromechanics.py
  tests/integration/models/test_thermoporomechanics.py
  tests/integration/models/test_well_models.py
  tests/integration/test_wells.py
Labels: PR - waiting on reviewer(s)

#843 BUG: Cartesian fracture meshing with intersections
  src/porepy/fracs/structured.py
  tests/integration/test_fracture_mesh_generation.py
Labels: bug-fix, PR - waiting on reviewer(s), review - short

#842 BUG: displacement jump aperture missed prolongation
  src/porepy/models/constitutive_laws.py
Labels: bug-fix, PR - waiting on reviewer(s), review - short

#844 Deprecate-contact-discretization
  .github/pull_request_template.md
  src/porepy/__init__.py
  src/porepy/grids/refinement.py
  src/porepy/models/geometry.py
  src/porepy/models/solution_strategy.py
  src/porepy/numerics/ad/discretizations.py
  src/porepy/numerics/fracture_deformation/contact_conditions.py
  src/porepy/numerics/fracture_deformation/propagate_fracture.py
  src/porepy/numerics/interface_laws/contact_mechanics_interface_laws.py
  src/porepy/numerics/linear_solvers.py
  src/porepy/numerics/nonlinear/nonlinear_solvers.py
  src/porepy/utils/tangential_normal_projection.py
  src/porepy/viz/diagnostics_mixin.py
  tests/integration/models/test_diagnostics_mixin.py
  tests/integration/test_fracture_propagation.py
  tutorials/exporter.ipynb
  tutorials/incompressible_flow_model.ipynb
  tutorials/simulation_exporting.ipynb
Labels: PR - waiting on reviewer(s), review - short
