Repository pmgbergen/porepy, pull requests merged in 2023-04, with the labels that each got.

#838 795 unify mixed dimensional grid generation (functionality)
  src/porepy/__init__.py
  src/porepy/grids/mdg_generation.py
  tests/integration/test_mdg_generation.py
Labels: enhancement

#851 846 inconsistency in fracture network 2d with domain = none
  src/porepy/fracs/fracture_network_2d.py
  src/porepy/grids/mdg_generation.py
  tests/integration/test_mdg_generation.py
Labels: bug-fix

#855 Restructuring applications sub package
  examples/mandel_biot.py
  examples/terzaghi_biot.py
  src/porepy/applications/building_blocks/derived_models/__init__.py
  src/porepy/models/derived_models/__init__.py
  src/porepy/models/derived_models/biot.py
  src/porepy/utils/dev_tools/__init__.py
  src/porepy/utils/dev_tools/models_glossary.py
  src/porepy/utils/examples_utils.py
  tests/functional/setups/manu_flow_comp_frac.py
  tests/functional/setups/manu_flow_incomp_frac.py
  tests/functional/setups/manu_poromech_nofrac.py
  tests/functional/test_mandel_biot.py
  tests/functional/test_terzaghi_biot.py
  tutorials/mandels_problem.ipynb
  tutorials/poromechanics_verifications.ipynb
Labels: enhancement, review - short

#839 Initialization of models from vtu/pvd
  src/porepy/models/momentum_balance.py
  src/porepy/models/poromechanics.py
  src/porepy/models/solution_strategy.py
  src/porepy/numerics/time_step_control.py
  src/porepy/viz/data_saving_model_mixin.py
  src/porepy/viz/exporter.py
  tests/integration/models/restart_reference/previous_data.pvd
  tests/integration/models/restart_reference/previous_times.json
  tests/integration/models/test_restart.py
  tests/unit/test_time_step_control.py
  tests/unit/test_vtk.py
  tests/unit/test_vtk_reference/restart/grid.pvd
  tests/unit/test_vtk_reference/restart/grid_000001.pvd
  tests/unit/test_vtk_reference/restart/grid_000002.pvd
  tests/unit/test_vtk_reference/restart/grid_1_000001.vtu
  tests/unit/test_vtk_reference/restart/grid_1_000002.vtu
  tests/unit/test_vtk_reference/restart/grid_2_000001.vtu
  tests/unit/test_vtk_reference/restart/grid_2_000002.vtu
  tests/unit/test_vtk_reference/restart/grid_mortar_1_000001.vtu
  tests/unit/test_vtk_reference/restart/grid_mortar_1_000002.vtu
  tests/unit/test_vtk_reference/restart/previous_grid.pvd
Labels: enhancement

#860 Application grids
  examples/mandel_biot.py
  examples/terzaghi_biot.py
  src/porepy/applications/md_grids/__init__.py
  src/porepy/applications/md_grids/domains.py
  src/porepy/applications/md_grids/fracture_sets.py
  src/porepy/applications/md_grids/mdg_library.py
  src/porepy/applications/md_grids/model_geometries.py
  src/porepy/fracs/fracture_network.py
  src/porepy/grids/mdg_generation.py
  src/porepy/models/geometry.py
  tests/functional/setups/manu_flow_incomp_frac.py
  tests/functional/setups/manu_poromech_nofrac.py
  tests/functional/test_manu_flow_comp_frac.py
  tests/functional/test_manu_flow_incomp_frac.py
  tests/functional/test_manu_poromech_nofrac.py
  tests/integration/models/setup_utils.py
  tests/integration/models/test_geometry.py
  tests/integration/models/test_poromechanics.py
  tests/integration/models/test_well_models.py
Labels: enhancement, PR - in progress

#865 Add networkx and sympy intersphinx mapping
  docs/conf.py
Labels: documentation

#863 Workflow to run skipped tests
  .github/pull_request_template.md
  .github/workflows/run-pytest-all.yml
  conftest.py
  tests/integration/models/test_constitutive_laws.py
  tests/integration/models/test_equations.py
Labels: enhancement, priority - high, test

#867 Allow for possibility to run workflows manually
  .github/workflows/push-develop-docker-image.yml
  .github/workflows/push-stable-docker-image.yml
  .github/workflows/run-pytest.yml
  .github/workflows/run-static-checks.yml
Labels: enhancement

#868 Mainetance of wells and boundary grids
  src/porepy/fracs/wells_3d.py
  src/porepy/grids/boundary_grid.py
  src/porepy/grids/md_grid.py
  src/porepy/numerics/ad/grid_operators.py
Labels: PR - waiting on author(s), review - short

#873 FEAT: Pass "meshing_arguments" from the model parameters
  src/porepy/models/geometry.py
Labels: PR - waiting on reviewer(s), review - short

#876 BUG: Replace @ by *
  src/porepy/models/constitutive_laws.py
Labels: bug-fix, PR - waiting on reviewer(s), review - short

#871 Tests for 3d manufactured solutions and observed order of convergence
  src/porepy/applications/convergence_analysis.py
  src/porepy/utils/txt_io.py
  tests/functional/setups/manu_flow_comp_2d_frac.py
  tests/functional/setups/manu_flow_comp_3d_frac.py
  tests/functional/setups/manu_flow_incomp_frac_2d.py
  tests/functional/setups/manu_flow_incomp_frac_3d.py
  tests/functional/setups/manu_poromech_nofrac_2d.py
  tests/functional/setups/manu_poromech_nofrac_3d.py
  tests/functional/test_mandel.py
  tests/functional/test_manu_flow_comp_frac.py
  tests/functional/test_manu_flow_incomp_frac.py
  tests/functional/test_manu_poromech_nofrac.py
  tests/functional/test_terzaghi.py
  tests/unit/test_convergence_analysis.py
  tests/unit/test_time_step_control.py
  tests/unit/test_txt_io.py
Labels: PR - waiting on reviewer(s), test
