Repository pmgbergen/porepy, pull requests merged in 2023-02, with the labels that each got.

#804 799 mandels verification setup
  src/porepy/applications/verification_setups/mandel_biot.py
  src/porepy/applications/verification_setups/manu_flow_comp_frac.py
  src/porepy/applications/verification_setups/manu_flow_incomp_frac.py
  src/porepy/applications/verification_setups/manu_poromech_nofrac.py
  src/porepy/applications/verification_setups/terzaghi_biot.py
  src/porepy/applications/verification_setups/verification_utils.py
  tests/functional/test_mandel_biot.py
  tests/functional/test_manu_flow_comp_frac.py
  tests/functional/test_manu_flow_incomp_frac.py
  tests/functional/test_manu_poromech_nofrac.py
  tutorials/poromechanics_verifications.ipynb
Labels: review - short, test

#809 Use fixtures to avoid running simulations on collection
  tests/functional/test_mandel_biot.py
  tests/functional/test_manu_flow_comp_frac.py
  tests/functional/test_manu_poromech_nofrac.py
Labels: PR - waiting on author(s)

#812 BUG: Indentation error in Ad maximum function.
  src/porepy/numerics/ad/functions.py
Labels: bug-fix, PR - waiting on reviewer(s), review - short

#815 807 restructuring of applications folder and verification setups
  src/porepy/applications/building_blocks/__init__.py
  src/porepy/applications/building_blocks/derived_models/__init__.py
  src/porepy/applications/building_blocks/derived_models/biot.py
  src/porepy/applications/building_blocks/models_glossary.py
  src/porepy/applications/building_blocks/verification_utils.py
  src/porepy/applications/complete_setups/__init__.py
  src/porepy/applications/complete_setups/mandel_biot.py
  src/porepy/applications/complete_setups/terzaghi_biot.py
  src/porepy/applications/verification_setups/verification_utils.py
  src/porepy/models/constitutive_laws.py
  src/porepy/models/mass_and_energy_balance.py
  src/porepy/models/old_models/__init__.py
  src/porepy/models/run_models.py
  src/porepy/models/units.py
  src/porepy/numerics/fv/biot.py
  src/porepy/numerics/fv/mpsa.py
  src/porepy/viz/data_saving_model_mixin.py
  tests/functional/setups/__init__.py
  tests/functional/setups/manu_flow_comp_frac.py
  tests/functional/setups/manu_flow_incomp_frac.py
  tests/functional/setups/manu_poromech_nofrac.py
  tests/functional/test_mandel_biot.py
  tests/functional/test_manu_flow_comp_frac.py
  tests/functional/test_manu_flow_incomp_frac.py
  tests/functional/test_manu_poromech_nofrac.py
  tests/functional/test_terzaghi_biot.py
  tests/integration/test_mpsa.py
  tutorials/poromechanics_verifications.ipynb
Labels: PR - waiting on reviewer(s)

#816 Unify fracture network generation [PR 1/2]
  src/porepy/__init__.py
  src/porepy/applications/complete_setups/mandel_biot.py
  src/porepy/fracs/fracture.py
  src/porepy/fracs/fracture_importer.py
  src/porepy/fracs/fracture_network.py
  src/porepy/fracs/fracture_network_2d.py
  src/porepy/fracs/fracture_network_3d.py
  src/porepy/fracs/plane_fracture.py
  src/porepy/fracs/utils.py
  src/porepy/fracs/wells_3d.py
  src/porepy/geometry/domain.py
  src/porepy/grids/standard_grids/utils.py
  tests/functional/setups/manu_flow_incomp_frac.py
  tests/functional/setups/manu_poromech_nofrac.py
  tests/integration/models/setup_utils.py
  tests/integration/models/test_constitutive_laws.py
  tests/integration/models/test_geometry.py
  tests/integration/test_fracture_mesh_generation.py
  tests/integration/test_grid_factory.py
  tests/integration/test_tag_gmsh.py
  tests/unit/test_darcy_mortar.py
  tests/unit/test_fracture_importer.py
  tests/unit/test_fracture_intersection.py
  tests/unit/test_fracture_network.py
  tests/unit/test_fracture_utils.py
  tests/unit/test_vtk.py
Labels: enhancement, PR - waiting on reviewer(s)

#821 Remove displacement trace methods from constitutive laws
  src/porepy/models/constitutive_laws.py
  src/porepy/models/old_models/__init__.py
Labels: review - short

#820 Rework of Ad framework, parsing and forward mode
  src/porepy/applications/building_blocks/verification_utils.py
  src/porepy/models/abstract_equations.py
  src/porepy/models/constitutive_laws.py
  src/porepy/models/energy_balance.py
  src/porepy/models/fluid_mass_balance.py
  src/porepy/models/geometry.py
  src/porepy/models/momentum_balance.py
  src/porepy/models/poromechanics.py
  src/porepy/numerics/ad/__init__.py
  src/porepy/numerics/ad/_ad_utils.py
  src/porepy/numerics/ad/discretizations.py
  src/porepy/numerics/ad/forward_mode.py
  src/porepy/numerics/ad/functions.py
  src/porepy/numerics/ad/grid_operators.py
  src/porepy/numerics/ad/operator_functions.py
  src/porepy/numerics/ad/operators.py
  tests/functional/setups/manu_flow_comp_frac.py
  tests/functional/setups/manu_flow_incomp_frac.py
  tests/functional/setups/manu_poromech_nofrac.py
  tests/integration/ad/test_equation_system_evaluation.py
  tests/integration/models/setup_utils.py
  tests/integration/models/test_constitutive_laws.py
  tests/integration/models/test_energy_balance.py
  tests/integration/models/test_geometry.py
  tests/integration/models/test_mass_balance.py
  tests/integration/test_ad.py
  tests/unit/ad/test_ad_array_forward_mode.py
  tests/unit/ad/test_ad_operator_tree.py
  tests/unit/ad/test_forward_ad_standard_functions.py
  tests/unit/ad/test_grid_operators.py
  tests/unit/test_equation_system.py
  tests/unit/test_mixed_dim_gravity.py
  tutorials/automatic_differentiation.ipynb
  tutorials/contact_mechanics_with_AD.ipynb
  tutorials/diagnostics.ipynb
  tutorials/equation_definition.ipynb
  tutorials/exporter.ipynb
  tutorials/models_v2.ipynb
Labels: PR - waiting on reviewer(s)
