Repository pmgbergen/porepy, pull requests merged in 2023-01, with the labels that each got.

#786 BUG: Update needed for networkx v3
  src/porepy/grids/partition.py
Labels: bug-fix, priority - high, PR - waiting on reviewer(s), review - short

#783 Docs update grids
  mypy.ini
  src/porepy/geometry/bounding_box.py
  src/porepy/geometry/constrain_geometry.py
  src/porepy/geometry/distances.py
  src/porepy/geometry/geometry_property_checks.py
  src/porepy/geometry/half_space.py
  src/porepy/geometry/intersections.py
  src/porepy/geometry/map_geometry.py
  src/porepy/geometry/point_in_polyhedron_test.py
  src/porepy/grids/__init__.py
  src/porepy/grids/boundary_grid.py
  src/porepy/grids/coarsening.py
  src/porepy/grids/grid.py
  src/porepy/grids/grid_extrusion.py
  src/porepy/grids/match_grids.py
  src/porepy/grids/md_grid.py
  src/porepy/grids/mortar_grid.py
  src/porepy/grids/partition.py
  src/porepy/grids/point_grid.py
  src/porepy/grids/refinement.py
  src/porepy/grids/simplex.py
  src/porepy/grids/standard_grids/md_grids_2d.py
  src/porepy/grids/structured.py
Labels: documentation

#790 Biot model subclass + Terzaghi verification setup
  src/porepy/applications/__init__.py
  src/porepy/applications/classic_models/__init__.py
  src/porepy/applications/classic_models/biot.py
  src/porepy/models/constitutive_laws.py
  src/porepy/models/material_constants.py
  src/porepy/models/verification_setups/terzaghi_biot.py
  src/porepy/models/verification_setups/verifications_utils.py
  tests/functional/__init__.py
  tests/functional/test_terzaghi_biot.py
Labels: enhancement, PR - in progress, review - short, test

#798 793 restructuring and reorganization of verification setups
  src/porepy/applications/derived_models/__init__.py
  src/porepy/applications/derived_models/biot.py
  src/porepy/applications/verification_setups/__init__.py
  src/porepy/applications/verification_setups/manu_flow_comp_frac.py
  src/porepy/applications/verification_setups/manu_flow_incomp_frac.py
  src/porepy/applications/verification_setups/manu_poromech_nofrac.py
  src/porepy/applications/verification_setups/terzaghi_biot.py
  src/porepy/applications/verification_setups/verification_utils.py
  src/porepy/models/solution_strategy.py
  src/porepy/models/verification_setups/manu_flow_comp_frac.py
  src/porepy/models/verification_setups/manu_flow_incomp_frac.py
  tests/functional/test_manu_flow_comp_frac.py
  tests/functional/test_manu_flow_incomp_frac.py
  tests/functional/test_manu_poromech_nofrac.py
  tests/functional/test_terzaghi_biot.py
Labels: review - short
